const now = new Date();
const ago = (d) => new Date(now.getTime() - d * 86400000).toISOString().slice(0, 10);
const inFuture = (d) => new Date(now.getTime() + d * 86400000).toISOString().slice(0, 10);
const todayStr = now.toISOString().slice(0, 10);

export function buildDemoJobs() {
  return [
    {
      id: 'demo-1', kode: 'DNP/2026/0001',
      klien: 'PT Equinix Indonesia (JKT05 Cikarang)', lokasi: 'Cikarang, Bekasi',
      owner_marketing: 'Terzha R. Perdanawan',
      pic_klien: 'Bapak Hendra (HSE)', pic_klien_phone: '0812-3456-7890',
      pesawat: 'Proteksi Kebakaran (Form 65 K)', units: 4, nilai: 85000000,
      termin_pembayaran: 'DP', dp_paid: true,
      no_po: 'PO/EQX/2026/0142', tgl_po: ago(15),
      stage: 5, stage_started_at: ago(2),
      inspektur: 'Rendi Pratama, Terzha R. Perdanawan',
      inspektur_ids: ['I001', 'I002'],
      tgl_pelaksanaan: ago(5),
      no_surat_tugas: 'ST-DNP/2026/0142', tgl_surat_tugas: ago(8),
      disnaker_tujuan: 'Disnaker Bekasi', tgl_h5: ago(10),
      h5_confirmed: true, h5_method: 'teman_k3',
      peer_review_status: 'submitted',
      laik_status: 'laik_bersyarat',
      evaluations: [
        { unit_no: 1, unit_label: 'Sprinkler Zona 1', status: 'laik', findings: 'Tekanan & flow normal', recommendation: 'Maintenance per 6 bulan' },
        { unit_no: 2, unit_label: 'Sprinkler Zona 2', status: 'laik', findings: 'Sesuai NFPA 25', recommendation: 'Lanjutkan rutinitas' },
        { unit_no: 3, unit_label: 'Fire Alarm Panel', status: 'laik_bersyarat', findings: 'Battery backup weak', recommendation: 'Ganti battery dalam 30 hari' },
        { unit_no: 4, unit_label: 'Hydrant System', status: 'laik', findings: 'Tekanan 5.5 bar OK', recommendation: 'Flushing per kuartal' },
      ],
      tgl_teknis_diserahkan: ago(4),
      tgl_laporan_mulai: ago(2),
      tgl_laporan_selesai: ago(1),
      created_at: ago(15), notes: 'Stage 5 (Delta): 3 milestone dates LHPP',
      documents: [
        { stage: 1, type: 'PO/SPK', name: 'PO-EQX-2026-0142.pdf', uploaded_at: ago(15), by: 'Marketing' },
        { stage: 5, type: 'LHPP', name: 'LHPP-Equinix-FIRE.pdf', uploaded_at: ago(2), by: 'Rendi Pratama' },
      ],
      history: [
        { stage: 1, ts: ago(15), by: 'Marketing', action: 'Job dibuat dari PO' },
        { stage: 5, ts: ago(1), by: 'Rendi Pratama', action: 'LHPP & BAP submit untuk peer review' },
      ],
    },
    {
      id: 'demo-2', kode: 'DNP/2026/0002',
      klien: 'Hotel Indonesia Kempinski', lokasi: 'Thamrin, Jakarta Pusat',
      owner_marketing: 'Andini Sari',
      pic_klien: 'Pak Surya (Chief Engineer)', pic_klien_phone: '0813-9876-5432',
      pesawat: 'Bejana Tekan (Form 45 A.1)', units: 4, nilai: 32000000,
      termin_pembayaran: 'FULL',
      no_po: 'PO/HIK/2026/0033', tgl_po: ago(40),
      stage: 8, stage_started_at: ago(25),
      inspektur: 'Terzha R. Perdanawan, Bambang Setiawan',
      inspektur_ids: ['I001', 'I003'],
      tgl_pelaksanaan: ago(30),
      no_surat_tugas: 'ST-DNP/2026/0033', disnaker_tujuan: 'Disnaker DKI Jakarta',
      peer_review_status: 'approved', laik_status: 'laik',
      units_tracking: [
        { unit_no: 1, unit_label: 'Calorifier Tower A (200L)', laik_status: 'laik', status: 'issued', tgl_submit: ago(25), no_registrasi: 'REG/DKI/PV/2026/045-U1', no_suket: 'SK.045A/DISNAKER/DKI/2026', tgl_suket: ago(8), suket_expired_at: inFuture(720), suket_validity_months: 24, notes: '' },
        { unit_no: 2, unit_label: 'Calorifier Tower B (200L)', laik_status: 'laik', status: 'issued', tgl_submit: ago(25), no_registrasi: 'REG/DKI/PV/2026/045-U2', no_suket: 'SK.045B/DISNAKER/DKI/2026', tgl_suket: ago(8), suket_expired_at: inFuture(720), suket_validity_months: 24, notes: '' },
      ],
      created_at: ago(40), notes: 'Proses Disnaker DKI Jakarta',
      history: [
        { stage: 1, ts: ago(40), by: 'Marketing', action: 'Job dibuat' },
        { stage: 8, ts: ago(5), by: 'Admin', action: 'Dokumen diproses di Disnaker DKI' },
      ],
    },
    {
      id: 'demo-3', kode: 'DNP/2026/0003',
      klien: 'PT Toyota Motor Manufacturing Indonesia', lokasi: 'Karawang',
      owner_marketing: 'Terzha R. Perdanawan',
      pic_klien: 'Ibu Linda (EHS Manager)', pic_klien_phone: '0811-2233-4455',
      pesawat: 'PAPA (Crane/Forklift/dll) (Form A 52)', units: 8, nilai: 64000000,
      termin_pembayaran: 'DP', dp_paid: false,
      no_po: 'PO/TMMIN/2026/0089', tgl_po: ago(5),
      stage: 2, stage_started_at: ago(3),
      created_at: ago(5), notes: 'Overhead crane 5 ton + forklift',
      history: [
        { stage: 1, ts: ago(5), by: 'Marketing', action: 'Job dibuat dari PO TMMIN' },
        { stage: 2, ts: ago(3), by: 'Admin Dokumen', action: 'Verifikasi checklist dokumen' },
      ],
    },
    {
      id: 'demo-4', kode: 'DNP/2026/0004',
      klien: 'PT Pupuk Kujang', lokasi: 'Cikampek',
      owner_marketing: 'Terzha R. Perdanawan',
      pic_klien: 'Bapak Arman', pic_klien_phone: '0812-7654-3210',
      pesawat: 'Pesawat Uap (Boiler) (Form 6)', units: 2, nilai: 48000000,
      termin_pembayaran: 'DP', dp_paid: true, pelunasan_paid: false,
      no_po: 'PO/PK/2026/0021', tgl_po: ago(120),
      stage: 15, stage_started_at: ago(2), // Stage 11c
      inspektur: 'Terzha R. Perdanawan, Rendi Pratama', tgl_pelaksanaan: ago(95),
      paid: false, invoice_no: 'INV-2026-0021', invoice_date: ago(2),
      created_at: ago(120), notes: 'Stage 11c Verifikasi Pembayaran: Menunggu validasi finance',
      history: [
        { stage: 11, ts: ago(3), by: 'Marketing', action: 'Penagihan dikirim ke Klien' },
        { stage: 15, ts: ago(2), by: 'Finance', action: 'Masuk Stage 11c: Cek Pelunasan Bank' },
      ],
    },
    {
      id: 'demo-5', kode: 'DNP/2026/0005',
      klien: 'Apartemen The Pakubuwono', lokasi: 'Jakarta Selatan',
      owner_marketing: 'Andini Sari',
      pic_klien: 'Pak Bambang (Building Manager)', pic_klien_phone: '0815-8888-9999',
      pesawat: 'Lift / Dumbwaiter (Form 36/38/39)', units: 6, nilai: 42000000,
      termin_pembayaran: 'FULL',
      no_po: 'PO/PKB/2026/0011', tgl_po: ago(8),
      stage: 3, stage_started_at: ago(7),
      created_at: ago(8), notes: 'Lift penumpang 6 unit (2 tower)',
      history: [
        { stage: 1, ts: ago(8), by: 'Marketing', action: 'Job dibuat' },
        { stage: 3, ts: ago(7), by: 'Admin RU', action: 'Penjadwalan tim inspektur' },
      ],
    },
    {
      id: 'demo-6', kode: 'DNP/2026/0006',
      klien: 'PT Astra Daihatsu Motor', lokasi: 'Sunter, Jakarta Utara',
      owner_marketing: 'Terzha R. Perdanawan',
      pic_klien: 'Pak Hermansyah (HSE Supervisor)', pic_klien_phone: '0817-5544-3322',
      pesawat: 'Instalasi Listrik & PP (Form 55 L)', units: 3, nilai: 28000000,
      termin_pembayaran: 'DP', dp_paid: true,
      no_po: 'PO/ADM/2026/0078', tgl_po: ago(6),
      stage: 4, stage_started_at: ago(1),
      inspektur: 'Sri Mulyani, Rendi Pratama', inspektur_ids: ['I005', 'I002'],
      tgl_pelaksanaan: todayStr,
      created_at: ago(6), notes: 'Panel listrik 3 unit sedang diinspeksi di lapangan',
      history: [
        { stage: 1, ts: ago(6), by: 'Marketing', action: 'Job dibuat dari PO Astra' },
        { stage: 4, ts: ago(1), by: 'Sri Mulyani', action: 'Tim Ahli tiba di lokasi' },
      ],
    },
    {
      id: 'demo-7', kode: 'DNP/2026/0007',
      klien: 'PT Indofood CBP Sukses Makmur', lokasi: 'Cibitung, Bekasi',
      owner_marketing: 'Andini Sari',
      pic_klien: 'Pak Hendro (Factory Manager)', pic_klien_phone: '0812-4455-6677',
      pesawat: 'PTP (Compressor/Genset) (Form 54 A)', units: 5, nilai: 35000000,
      termin_pembayaran: 'DP', dp_paid: true,
      no_po: 'PO/ICBP/2026/0045', tgl_po: ago(12),
      stage: 13, stage_started_at: ago(4), // Stage 4b Aktualisasi Unit
      inspektur: 'Andi Wijaya',
      created_at: ago(12), notes: 'Stage 4b: Ditemukan 1 unit genset tambahan di lapangan (perlu aktualisasi)',
      history: [
        { stage: 4, ts: ago(5), by: 'Andi Wijaya', action: 'Inspeksi selesai: unit berbeda dari PO' },
        { stage: 13, ts: ago(4), by: 'Marketing', action: 'Masuk Stage 4b: Menyesuaikan kuota unit dengan Klien' },
      ],
    },
    {
      id: 'demo-8', kode: 'DNP/2026/0008',
      klien: 'PT Unilever Indonesia Tbk', lokasi: 'BSD City, Tangerang',
      owner_marketing: 'Terzha R. Perdanawan',
      pic_klien: 'Ibu Ratna (Facility Head)', pic_klien_phone: '0813-1122-3344',
      pesawat: 'Eskalator / Travelator (Form 52)', units: 4, nilai: 36000000,
      termin_pembayaran: 'FULL',
      no_po: 'PO/ULI/2026/0112', tgl_po: ago(20),
      stage: 6, stage_started_at: ago(2), // Stage 6 Review Laporan Teknis
      inspektur: 'Bambang Setiawan',
      created_at: ago(20), notes: 'LHPP selesai, menunggu review dan tanda tangan Kadiv RU',
      history: [
        { stage: 5, ts: ago(3), by: 'Bambang Setiawan', action: 'Draft LHPP diunggah' },
        { stage: 6, ts: ago(2), by: 'Kadiv RU', action: 'Review teknis laporan' },
      ],
    },
    {
      id: 'demo-9', kode: 'DNP/2026/0009',
      klien: 'PT Kalbe Farma Tbk', lokasi: 'Cikarang Barat',
      owner_marketing: 'Andini Sari',
      pic_klien: 'Pak Dodi (Engineering QA)', pic_klien_phone: '0818-3344-5566',
      pesawat: 'Bejana Tekan (Form 45 A.1)', units: 3, nilai: 27000000,
      termin_pembayaran: 'DP', dp_paid: true,
      no_po: 'PO/KLBF/2026/0091', tgl_po: ago(30),
      stage: 7, stage_started_at: ago(3), // Stage 7 Verifikasi ke Dinas
      created_at: ago(30), notes: 'Admin RU mempersiapkan penyerahan berkas ke Disnaker Bekasi',
      history: [
        { stage: 6, ts: ago(4), by: 'Kadiv RU', action: 'Laporan disetujui Kadiv' },
        { stage: 7, ts: ago(3), by: 'Admin RU', action: 'Penyerahan berkas fisik ke Disnaker' },
      ],
    },
    {
      id: 'demo-10', kode: 'DNP/2026/0010',
      klien: 'PT Mayora Indah Tbk', lokasi: 'Balaraja, Tangerang',
      owner_marketing: 'Terzha R. Perdanawan',
      pic_klien: 'Pak Gunawan (Plant Head)', pic_klien_phone: '0812-9988-7766',
      pesawat: 'Pesawat Uap (Boiler) (Form 6)', units: 2, nilai: 50000000,
      termin_pembayaran: 'FULL',
      no_po: 'PO/MYOR/2026/0034', tgl_po: ago(45),
      stage: 9, stage_started_at: ago(5), // Stage 9 Pengurusan Suket
      tgl_input_suket: ago(5),
      tgl_suket_selesai: null,
      created_at: ago(45), notes: 'Disnaker selesai, menunggu penomoran Suket resmi',
      history: [
        { stage: 8, ts: ago(6), by: 'Disnaker', action: 'Disetujui Disnaker Banten' },
        { stage: 9, ts: ago(5), by: 'Admin', action: 'Pengurusan cetak & legalisir Suket' },
      ],
    },
    {
      id: 'demo-11', kode: 'DNP/2026/0011',
      klien: 'PT Santos Jaya Abadi (Kapal Api)', lokasi: 'Karawang International City',
      owner_marketing: 'Andini Sari',
      pic_klien: 'Pak Arif (HSE)', pic_klien_phone: '0813-4433-2211',
      pesawat: 'PAPA (Crane/Forklift/dll) (Form A 52)', units: 6, nilai: 48000000,
      termin_pembayaran: 'DP', dp_paid: true,
      no_po: 'PO/SJA/2026/0067', tgl_po: ago(50),
      stage: 10, stage_started_at: ago(2), // Stage 10 Pembuatan Invoice
      invoice_no: 'INV-2026-0067',
      total_invoice_amount: 48000000,
      tgl_invoice_issued: ago(2),
      created_at: ago(50), notes: 'Suket sudah terbit, Finance menerbitkan invoice penagihan',
      history: [
        { stage: 9, ts: ago(3), by: 'Admin', action: 'Suket selesai' },
        { stage: 10, ts: ago(2), by: 'Finance', action: 'Pembuatan Invoice Pelunasan' },
      ],
    },
    {
      id: 'demo-12', kode: 'DNP/2026/0012',
      klien: 'PT Nestle Indonesia', lokasi: 'Karawang',
      owner_marketing: 'Terzha R. Perdanawan',
      pic_klien: 'Ibu Maya (Finance Dept)', pic_klien_phone: '0811-9988-2233',
      pesawat: 'Proteksi Kebakaran (Form 65 K)', units: 5, nilai: 60000000,
      termin_pembayaran: 'FULL',
      no_po: 'PO/NST/2026/0088', tgl_po: ago(60),
      stage: 11, stage_started_at: ago(4), // Stage 11 Penagihan
      invoice_no: 'INV-2026-0088',
      total_invoice_amount: 60000000,
      tgl_invoice_issued: ago(5),
      payment_retry_count: 0,
      created_at: ago(60), notes: 'Invoice terkirim, follow up pembayaran ke Finance Klien',
      history: [
        { stage: 10, ts: ago(5), by: 'Finance', action: 'Invoice INV-2026-0088 terbit' },
        { stage: 11, ts: ago(4), by: 'Marketing', action: 'Follow-up penagihan' },
      ],
    },
    {
      id: 'demo-13', kode: 'DNP/2026/0013',
      klien: 'PT Gudang Garam Tbk', lokasi: 'Kediri / Jakarta',
      owner_marketing: 'Andini Sari',
      pic_klien: 'Pak Wibowo', pic_klien_phone: '0812-6677-8899',
      pesawat: 'Lift / Dumbwaiter (Form 36/38/39)', units: 4, nilai: 32000000,
      termin_pembayaran: 'DP', dp_paid: true, pelunasan_paid: true,
      no_po: 'PO/GG/2026/0019', tgl_po: ago(70),
      stage: 14, stage_started_at: ago(1), // Stage 11b Pengiriman SUKET
      payment_status: 'lunas',
      no_resi: 'JNE-88219382101',
      ekspedisi: 'JNE Reguler',
      tgl_kirim_suket: ago(1),
      batch_delivery_no: 'BATCH-2026-001',
      created_at: ago(70), notes: 'Pembayaran lunas! Siap mengirimkan dokumen Suket asli ke Klien',
      documents: [
        { stage: 14, type: 'Bukti Pengiriman SUKET (Resi)', name: 'Resi-JNE-88219382101.jpg', uploaded_at: ago(1), by: 'Marketing' },
        { stage: 14, type: 'Tanda Terima SUKET dari Klien', name: 'Tanda-Terima-Klien.pdf', uploaded_at: ago(1), by: 'Marketing' },
      ],
      history: [
        { stage: 15, ts: ago(2), by: 'Finance', action: 'Pembayaran diverifikasi LUNAS' },
        { stage: 14, ts: ago(1), by: 'Marketing', action: 'Pengiriman dokumen Suket via Kurir' },
      ],
    },
    {
      id: 'demo-14', kode: 'DNP/2026/0014',
      klien: 'PT Danone Indonesia', lokasi: 'Sentul, Bogor',
      owner_marketing: 'Terzha R. Perdanawan',
      pic_klien: 'Pak Farhan', pic_klien_phone: '0815-1122-4455',
      pesawat: 'Instalasi Listrik & PP (Form 55 L)', units: 2, nilai: 20000000,
      termin_pembayaran: 'FULL',
      no_po: 'PO/DNN/2026/0002', tgl_po: ago(90),
      stage: 12, stage_started_at: ago(10), // Stage 12 Closed / Selesai
      created_at: ago(90), notes: 'Job selesai tuntas, Suket diterima klien dan pembayaran lunas',
      history: [
        { stage: 14, ts: ago(12), by: 'Marketing', action: 'Suket diterima klien (Tanda Terima OK)' },
        { stage: 12, ts: ago(10), by: 'Finance', action: 'Job Ditutup (Closed)' },
      ],
    },
    {
      id: 'demo-15', kode: 'DNP/2026/0015',
      klien: 'PT Chandra Asri Petrochemical', lokasi: 'Cilegon, Banten',
      owner_marketing: 'Andini Sari',
      pic_klien: 'Pak Suryanto (Safety Director)', pic_klien_phone: '0811-7788-9900',
      pesawat: 'Bejana Tekan (Form 45 A.1)', units: 6, nilai: 72000000,
      termin_pembayaran: 'DP', dp_paid: false,
      no_po: 'PO/CAP/2026/0199', tgl_po: ago(2),
      stage: 1, stage_started_at: ago(2), // Stage 1 PO Baru
      created_at: ago(2), notes: 'Job baru PO diterima, menunggu verifikasi dokumen dan DP',
      history: [
        { stage: 1, ts: ago(2), by: 'Marketing', action: 'Input data PO / SPK baru' },
      ],
    },
    {
      id: 'demo-16', kode: 'DNP/2026/0016',
      klien: 'PT Toyota Astra Motor (TAM Karawang)', lokasi: 'KIIC Karawang Barat',
      owner_marketing: 'Terzha R. Perdanawan',
      pic_klien: 'Pak Ridwan (HSE Section Head)', pic_klien_phone: '0812-9988-1122',
      pesawat: 'PAPA (Crane/Forklift/dll) (Form A 52)', units: 4, nilai: 38000000,
      termin_pembayaran: 'DP', dp_paid: true,
      no_po: 'PO/TAM/2026/0099', tgl_po: ago(14),
      stage: 16, stage_started_at: ago(2), // Stage 4c Penjadwalan Ulang (Reschedule)
      reschedule_reason: 'Unit belum siap / rusak di lokasi',
      tgl_reschedule: inFuture(3),
      reschedule_notes: '1 unit overhead crane sedang dalam penggantian wire rope oleh vendor',
      actual_units: 4,
      inspektur: 'Rendi Pratama',
      created_at: ago(14), notes: 'Stage 4c (Delta): Menjadwalkan ulang riksa uji untuk unit tertunda',
      history: [
        { stage: 4, ts: ago(4), by: 'Rendi Pratama', action: 'RU Selesai sebagian, 1 crane butuh reschedule' },
        { stage: 13, ts: ago(3), by: 'Marketing', action: 'Aktualisasi data unit diverifikasi' },
        { stage: 16, ts: ago(2), by: 'Admin', action: 'Masuk Stage 4c: Penjadwalan Ulang RU' },
      ],
    },
    {
      id: 'demo-17', kode: 'DNP/2026/0017',
      klien: 'PT Mayora Indah Divisi Biskuit', lokasi: 'Balaraja, Tangerang',
      owner_marketing: 'Andini Sari',
      pic_klien: 'Ibu Siska (Safety Officer)', pic_klien_phone: '0817-2233-4411',
      pesawat: 'Pesawat Uap (Boiler) (Form 6)', units: 2, nilai: 44000000,
      termin_pembayaran: 'FULL',
      no_po: 'PO/MYR/2026/0071', tgl_po: ago(18),
      stage: 17, stage_started_at: ago(1), // Stage 4d Riksa Uji Ulang
      ru_ulang_status: 'lolos',
      ru_ulang_notes: 'Pemeriksaan ulang ketel uap unit #2 selesai dengan hasil lolos uji hydrotest',
      inspektur: 'Bambang Setiawan',
      created_at: ago(18), notes: 'Stage 4d (Delta): Pelaksanaan Riksa Uji Ulang oleh Tim Ahli',
      documents: [
        { stage: 17, type: 'BAP RU Ulang', name: 'BAP-RU-Ulang-Boiler-2.pdf', uploaded_at: ago(1), by: 'Bambang Setiawan' },
        { stage: 17, type: 'Foto Pelaksanaan RU Ulang', name: 'Foto-Hydrotest-Boiler.jpg', uploaded_at: ago(1), by: 'Bambang Setiawan' },
      ],
      history: [
        { stage: 16, ts: ago(3), by: 'Admin', action: 'Jadwal RU Ulang ditetapkan' },
        { stage: 17, ts: ago(1), by: 'Bambang Setiawan', action: 'Tim Ahli melaksanakan RU Ulang di pabrik' },
      ],
    },
  ];
}
