const now = new Date();
const ago = (d) => new Date(now.getTime() - d * 86400000).toISOString().slice(0, 10);
const inFuture = (d) => new Date(now.getTime() + d * 86400000).toISOString().slice(0, 10);
const todayStr = now.toISOString().slice(0, 10);

export function buildDemoJobs() {
  return [
    {
      id: 'demo-1', kode: 'DNP/2026/0001',
      klien: 'PT Equinix Indonesia (JKT05 Cikarang)', lokasi: 'Cikarang, Bekasi',
      owner_marketing: 'Terzha R. Perdanawan',
      pic_klien: 'Bapak Hendra (HSE)', pic_klien_phone: '0812-3456-7890',
      pesawat: 'FIRE', units: 4, nilai: 85000000,
      no_po: 'PO/EQX/2026/0142', tgl_po: ago(15),
      stage: 5, stage_started_at: ago(2),
      inspektur: 'Rendi Pratama, Terzha R. Perdanawan',
      inspektur_ids: ['I001', 'I002'],
      tgl_pelaksanaan: ago(5),
      no_surat_tugas: 'ST-DNP/2026/0142', tgl_surat_tugas: ago(8),
      disnaker_tujuan: 'Disnaker Bekasi', tgl_h5: ago(10),
      h5_confirmed: true, h5_method: 'teman_k3',
      h5_confirmed_at: ago(10), h5_confirmed_by: 'Admin RU',
      peer_review_status: 'submitted',
      peer_review_submitted_at: ago(1), peer_review_submitted_by: 'Rendi Pratama',
      laik_status: 'laik_bersyarat',
      evaluations: [
        { unit_no: 1, unit_label: 'Sprinkler Zona 1', status: 'laik', findings: 'Tekanan & flow normal', recommendation: 'Maintenance per 6 bulan' },
        { unit_no: 2, unit_label: 'Sprinkler Zona 2', status: 'laik', findings: 'Sesuai NFPA 25', recommendation: 'Lanjutkan rutinitas' },
        { unit_no: 3, unit_label: 'Fire Alarm Panel', status: 'laik_bersyarat', findings: 'Battery backup 1 zone weak', recommendation: 'Ganti battery dalam 30 hari' },
        { unit_no: 4, unit_label: 'Hydrant System', status: 'laik', findings: 'Tekanan 5.5 bar OK', recommendation: 'Flushing per kuartal' },
      ],
      created_at: ago(15), notes: 'Sprinkler + Fire Alarm + Hydrant 4 sistem',
      documents: [
        { stage: 1, type: 'PO/SPK', name: 'PO-EQX-2026-0142.pdf', uploaded_at: ago(15), by: 'Marketing' },
        { stage: 5, type: 'LHPP', name: 'LHPP-Equinix-FIRE.pdf', uploaded_at: ago(2), by: 'Rendi Pratama' },
      ],
      history: [
        { stage: 1, ts: ago(15), by: 'Marketing', action: 'Job dibuat dari PO' },
        { stage: 5, ts: ago(1), by: 'Rendi Pratama', action: 'LHPP & BAP submit untuk peer review' },
      ],
    },
    {
      id: 'demo-2', kode: 'DNP/2026/0002',
      klien: 'Hotel Indonesia Kempinski', lokasi: 'Thamrin, Jakarta Pusat',
      owner_marketing: 'Andini Sari',
      pic_klien: 'Pak Surya (Chief Engineer)', pic_klien_phone: '0813-9876-5432',
      pesawat: 'PV', units: 4, nilai: 32000000,
      no_po: 'PO/HIK/2026/0033', tgl_po: ago(40),
      stage: 6, stage_started_at: ago(25),
      inspektur: 'Terzha R. Perdanawan, Bambang Setiawan',
      inspektur_ids: ['I001', 'I003'],
      tgl_pelaksanaan: ago(30),
      no_surat_tugas: 'ST-DNP/2026/0033', disnaker_tujuan: 'Disnaker DKI Jakarta',
      h5_confirmed: true, h5_method: 'teman_k3',
      peer_review_status: 'approved', peer_review_approved_at: ago(27),
      peer_review_approved_by: 'Terzha R. Perdanawan', laik_status: 'laik',
      units_tracking: [
        { unit_no: 1, unit_label: 'Calorifier Tower A (200L)', laik_status: 'laik', status: 'issued', tgl_submit: ago(25), no_registrasi: 'REG/DKI/PV/2026/045-U1', no_suket: 'SK.045A/DISNAKER/DKI/2026', tgl_suket: ago(8), suket_expired_at: inFuture(720), suket_validity_months: 24, notes: '' },
        { unit_no: 2, unit_label: 'Calorifier Tower B (200L)', laik_status: 'laik', status: 'issued', tgl_submit: ago(25), no_registrasi: 'REG/DKI/PV/2026/045-U2', no_suket: 'SK.045B/DISNAKER/DKI/2026', tgl_suket: ago(8), suket_expired_at: inFuture(720), suket_validity_months: 24, notes: '' },
        { unit_no: 3, unit_label: 'Storage Tank 500L (Kitchen)', laik_status: 'laik', status: 'submitted', tgl_submit: ago(25), no_registrasi: 'REG/DKI/PV/2026/045-U3', no_suket: null, tgl_suket: null, suket_expired_at: null, suket_validity_months: null, notes: '' },
        { unit_no: 4, unit_label: 'Pressure Vessel Spa (Hydrotest)', laik_status: 'laik_bersyarat', status: 'rejected', tgl_submit: ago(25), no_registrasi: 'REG/DKI/PV/2026/045-U4', no_suket: null, tgl_suket: null, suket_expired_at: null, suket_validity_months: null, notes: 'Disnaker minta data hydrotest lengkap' },
      ],
      evaluations: [
        { unit_no: 1, unit_label: 'Calorifier Tower A (200L)', status: 'laik', findings: 'ASME UG-27 OK', recommendation: 'Rutin' },
        { unit_no: 2, unit_label: 'Calorifier Tower B (200L)', status: 'laik', findings: 'ASME UG-27 OK', recommendation: 'Rutin' },
        { unit_no: 3, unit_label: 'Storage Tank 500L (Kitchen)', status: 'laik', findings: 'Ketebalan plat masih dalam toleransi', recommendation: 'Rutin' },
        { unit_no: 4, unit_label: 'Pressure Vessel Spa (Hydrotest)', status: 'laik_bersyarat', findings: 'Hydrotest tahunan diperlukan', recommendation: 'Hydrotest setiap 1 thn' },
      ],
      disnaker_followups: [
        { ts: new Date(Date.now() - 18*86400000).toISOString(), by: 'Admin RU', status: 'progress', notes: 'Telp Bu Ani (Disnaker DKI): 4 unit sudah masuk antrian review' },
        { ts: new Date(Date.now() - 8*86400000).toISOString(), by: 'Kadiv RU', status: 'progress', notes: 'Unit 4 ditolak karena dokumen kurang' },
      ],
      created_at: ago(40), notes: 'Calorifier 4 unit, mixed pemeriksaan luar & hydrotest',
      documents: [
        { stage: 1, type: 'PO/SPK', name: 'PO-HIK-2026-0033.pdf', uploaded_at: ago(40), by: 'Marketing' },
        { stage: 6, type: 'Bundel Dokumen Suket', name: 'Bundel-Suket-HIK.zip', uploaded_at: ago(24), by: 'Kadiv RU' },
      ],
      history: [
        { stage: 1, ts: ago(40), by: 'Marketing', action: 'Job dibuat' },
        { stage: 6, ts: ago(5), by: 'Kadiv RU', action: 'Unit 4 (PV Spa) DITOLAK Disnaker' },
      ],
    },
    {
      id: 'demo-3', kode: 'DNP/2026/0003',
      klien: 'PT Toyota Motor Manufacturing Indonesia', lokasi: 'Karawang',
      owner_marketing: 'Terzha R. Perdanawan',
      pic_klien: 'Ibu Linda (EHS Manager)', pic_klien_phone: '0811-2233-4455',
      pesawat: 'PAPA', units: 8, nilai: 64000000,
      no_po: 'PO/TMMIN/2026/0089', tgl_po: ago(5),
      stage: 2, stage_started_at: ago(3),
      inspektur: '', tgl_pelaksanaan: '',
      created_at: ago(5), notes: 'Overhead crane 5 ton + forklift 3 unit',
      documents: [{ stage: 1, type: 'PO/SPK', name: 'PO-TMMIN-2026-0089.pdf', uploaded_at: ago(5), by: 'Marketing' }],
      history: [
        { stage: 1, ts: ago(5), by: 'Marketing', action: 'Job dibuat dari PO TMMIN' },
        { stage: 2, ts: ago(3), by: 'Admin Dokumen', action: 'Menunggu Form Checklist klien' },
      ],
    },
    {
      id: 'demo-4', kode: 'DNP/2026/0004',
      klien: 'PT Pupuk Kujang', lokasi: 'Cikampek',
      owner_marketing: 'Terzha R. Perdanawan',
      pic_klien: 'Bapak Arman', pic_klien_phone: '0812-7654-3210',
      pesawat: 'BOILER', units: 2, nilai: 48000000,
      no_po: 'PO/PK/2026/0021', tgl_po: ago(120),
      stage: 7, stage_started_at: ago(2), completed_at: ago(1),
      inspektur: 'Terzha R. Perdanawan, Rendi Pratama', tgl_pelaksanaan: ago(95),
      units_tracking: [
        { unit_no: 1, unit_label: 'Boiler Pipa Air #1 (5 ton/jam)', laik_status: 'laik', status: 'issued', tgl_submit: ago(60), no_registrasi: 'REG/JABAR/BOILER/2026/021-U1', no_suket: 'SK.123A/DISNAKER/JABAR/2026', tgl_suket: ago(5), suket_expired_at: inFuture(360), suket_validity_months: 12, notes: '' },
        { unit_no: 2, unit_label: 'Boiler Pipa Air #2 (5 ton/jam)', laik_status: 'laik', status: 'issued', tgl_submit: ago(60), no_registrasi: 'REG/JABAR/BOILER/2026/021-U2', no_suket: 'SK.123B/DISNAKER/JABAR/2026', tgl_suket: ago(5), suket_expired_at: inFuture(360), suket_validity_months: 12, notes: '' },
      ],
      paid: false, invoice_no: 'INV-2026-0021', invoice_date: ago(2), top_days: 30,
      payment_due_date: inFuture(28), payment_status: 'sent',
      payment_paid_at: null, payment_amount_received: 0, tanda_terima_kembali: true,
      created_at: ago(120), notes: 'Boiler pipa air 2 unit kapasitas 5 ton/jam',
      documents: [
        { stage: 5, type: 'LHPP', name: 'LHPP-PK-Boiler.pdf', uploaded_at: ago(90), by: 'Tim Ahli' },
        { stage: 7, type: 'Invoice', name: 'INV-2026-0021.pdf', uploaded_at: ago(2), by: 'Adm. Keuangan' },
      ],
      history: [
        { stage: 6, ts: ago(5), by: 'Kadiv RU', action: 'Suket 2 unit TERBIT (1 tahun masing-masing)' },
        { stage: 7, ts: ago(1), by: 'Adm. Keuangan', action: 'Suket diserahkan, job selesai' },
      ],
    },
    {
      id: 'demo-5', kode: 'DNP/2026/0005',
      klien: 'Apartemen The Pakubuwono', lokasi: 'Jakarta Selatan',
      owner_marketing: 'Andini Sari',
      pic_klien: 'Pak Bambang (Building Manager)', pic_klien_phone: '0815-8888-9999',
      pesawat: 'LIFT', units: 6, nilai: 42000000,
      no_po: 'PO/PKB/2026/0011', tgl_po: ago(8),
      stage: 3, stage_started_at: ago(7),
      inspektur: '', tgl_pelaksanaan: inFuture(3),
      created_at: ago(8), notes: 'Lift penumpang 6 unit (2 tower)',
      documents: [
        { stage: 1, type: 'PO/SPK', name: 'PO-PKB-2026-0011.pdf', uploaded_at: ago(8), by: 'Marketing' },
        { stage: 2, type: 'Manual Book', name: 'Manual-Lift-Mitsubishi.pdf', uploaded_at: ago(6), by: 'Admin' },
      ],
      history: [
        { stage: 1, ts: ago(8), by: 'Marketing', action: 'Job dibuat' },
        { stage: 3, ts: ago(7), by: 'Admin RU', action: 'OVERDUE: belum assign inspektur' },
      ],
    },
    {
      id: 'demo-6', kode: 'DNP/2026/0006',
      klien: 'PT Astra Daihatsu Motor', lokasi: 'Sunter, Jakarta Utara',
      owner_marketing: 'Terzha R. Perdanawan',
      pic_klien: 'Pak Hermansyah (HSE Supervisor)', pic_klien_phone: '0817-5544-3322',
      pesawat: 'LISTRIK', units: 3, nilai: 28000000,
      no_po: 'PO/ADM/2026/0078', tgl_po: ago(6),
      stage: 4, stage_started_at: ago(1),
      inspektur: 'Sri Mulyani, Rendi Pratama', inspektur_ids: ['I005', 'I002'],
      tgl_pelaksanaan: todayStr, jam_mulai: '08:00', durasi_hari: 2,
      no_surat_tugas: 'ST-DNP/2026/0078', tgl_surat_tugas: ago(3),
      disnaker_tujuan: 'Disnaker DKI Jakarta', tgl_h5: ago(5),
      h5_confirmed: true, h5_method: 'teman_k3', h5_confirmed_at: ago(5), h5_confirmed_by: 'Admin RU',
      alat_ids: ['A002', 'A003', 'A004', 'A005'], cert_ids: ['CERT1', 'CERT3'],
      created_at: ago(6), notes: 'Panel listrik 3 unit (Main Panel, Sub Panel A, Sub Panel B)',
      documents: [
        { stage: 1, type: 'PO/SPK', name: 'PO-ADM-2026-0078.pdf', uploaded_at: ago(6), by: 'Marketing' },
        { stage: 3, type: 'Surat Tugas', name: 'ST-2026-0078.pdf', uploaded_at: ago(3), by: 'Admin RU' },
      ],
      history: [
        { stage: 1, ts: ago(6), by: 'Marketing', action: 'Job dibuat dari PO Astra' },
        { stage: 4, ts: ago(1), by: 'Sri Mulyani', action: 'Tim Ahli tiba di lokasi, mulai pelaksanaan' },
      ],
    },
    {
      id: 'demo-7', kode: 'DNP/2025/0089',
      klien: 'PT Maju Jaya Steel', lokasi: 'Karawang',
      owner_marketing: 'Andini Sari',
      pic_klien: 'Pak Joko (Procurement)', pic_klien_phone: '0815-7777-8888',
      pesawat: 'PAPA', units: 5, nilai: 55000000,
      no_po: 'PO/MJS/2025/0089', tgl_po: ago(150),
      stage: 7, stage_started_at: ago(60),
      inspektur: 'Andi Wijaya, Bambang Setiawan', inspektur_ids: ['I004', 'I003'],
      tgl_pelaksanaan: ago(120),
      no_surat_tugas: 'ST-DNP/2025/0089', disnaker_tujuan: 'Disnaker Jabar',
      h5_confirmed: true, h5_method: 'manual', peer_review_status: 'approved', laik_status: 'laik',
      units_tracking: [
        { unit_no: 1, unit_label: 'Overhead Crane 5T #1', laik_status: 'laik', status: 'issued', tgl_submit: ago(95), no_suket: 'SK.221A/JABAR/2025', tgl_suket: ago(65), suket_expired_at: inFuture(300), suket_validity_months: 12, notes: '' },
        { unit_no: 2, unit_label: 'Overhead Crane 5T #2', laik_status: 'laik', status: 'issued', tgl_submit: ago(95), no_suket: 'SK.221B/JABAR/2025', tgl_suket: ago(65), suket_expired_at: inFuture(300), suket_validity_months: 12, notes: '' },
        { unit_no: 3, unit_label: 'Forklift Toyota 3T', laik_status: 'laik', status: 'issued', tgl_submit: ago(95), no_suket: 'SK.221C/JABAR/2025', tgl_suket: ago(65), suket_expired_at: inFuture(300), suket_validity_months: 12, notes: '' },
        { unit_no: 4, unit_label: 'Forklift Komatsu 2.5T', laik_status: 'laik', status: 'issued', tgl_submit: ago(95), no_suket: 'SK.221D/JABAR/2025', tgl_suket: ago(65), suket_expired_at: inFuture(300), suket_validity_months: 12, notes: '' },
        { unit_no: 5, unit_label: 'Hoist Chain 2T', laik_status: 'laik', status: 'issued', tgl_submit: ago(95), no_suket: 'SK.221E/JABAR/2025', tgl_suket: ago(65), suket_expired_at: inFuture(300), suket_validity_months: 12, notes: '' },
      ],
      paid: false, invoice_no: 'INV-2025-0089', invoice_date: ago(50), top_days: 30,
      payment_due_date: ago(20), payment_status: 'overdue',
      payment_paid_at: null, payment_amount_received: 0, tanda_terima_kembali: false,
      created_at: ago(150), notes: 'Crane 2 unit + Forklift 2 unit + Hoist 1 unit',
      documents: [{ stage: 7, type: 'Invoice', name: 'INV-2025-0089.pdf', uploaded_at: ago(50), by: 'Putri Wahyuni' }],
      history: [
        { stage: 7, ts: ago(50), by: 'Putri Wahyuni', action: 'Invoice INV-2025-0089 terbit (Rp 55jt, TOP 30 hari)' },
        { stage: 7, ts: ago(28), by: 'Putri Wahyuni', action: 'Konfirmasi sampai - menunggu tanda terima kembali' },
      ],
    },
    {
      id: 'demo-8', kode: 'DNP/2025/0102',
      klien: 'PT Indomarco Adi Prima', lokasi: 'Cibitung, Bekasi',
      owner_marketing: 'Terzha R. Perdanawan',
      pic_klien: 'Bu Hanni (Finance)', pic_klien_phone: '0816-5544-3322',
      pesawat: 'LIFT', units: 2, nilai: 18000000,
      no_po: 'PO/IAP/2025/0102', tgl_po: ago(100),
      stage: 7, stage_started_at: ago(35),
      inspektur: 'Andi Wijaya', inspektur_ids: ['I004'],
      tgl_pelaksanaan: ago(80),
      no_surat_tugas: 'ST-DNP/2025/0102', disnaker_tujuan: 'Disnaker Jabar',
      h5_confirmed: true, h5_method: 'teman_k3', peer_review_status: 'approved', laik_status: 'laik',
      units_tracking: [
        { unit_no: 1, unit_label: 'Lift Penumpang Gedung A', laik_status: 'laik', status: 'issued', tgl_submit: ago(60), no_suket: 'SK.341A/JABAR/2025', tgl_suket: ago(38), suket_expired_at: inFuture(327), suket_validity_months: 12, notes: '' },
        { unit_no: 2, unit_label: 'Lift Penumpang Gedung B', laik_status: 'laik', status: 'issued', tgl_submit: ago(60), no_suket: 'SK.341B/JABAR/2025', tgl_suket: ago(38), suket_expired_at: inFuture(327), suket_validity_months: 12, notes: '' },
      ],
      paid: false, invoice_no: 'INV-2025-0102', invoice_date: ago(20), top_days: 30,
      payment_due_date: inFuture(10), payment_status: 'sent',
      payment_paid_at: null, payment_amount_received: 0, tanda_terima_kembali: true,
      created_at: ago(100), notes: 'Lift penumpang 2 unit gedung kantor',
      documents: [{ stage: 7, type: 'Invoice', name: 'INV-2025-0102.pdf', uploaded_at: ago(20), by: 'Putri Wahyuni' }],
      history: [
        { stage: 7, ts: ago(20), by: 'Putri Wahyuni', action: 'Invoice INV-2025-0102 terbit' },
        { stage: 7, ts: ago(12), by: 'Putri Wahyuni', action: 'Tanda terima kurir kembali' },
      ],
    },
  ];
}
